{
 "title": "Table minimize",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "select distinct country from devices;"
   },
   {
    "name": "state",
    "label": "State",
    "query": "select distinct state from devices where country in ($country);"
   },
   {
    "name": "city",
    "label": "City",
    "query": "select distinct city from devices where country in ($country) and state in ($state);"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "select distinct name from devices where country in ($country) and state in ($state) and city in ($city);"
   },
   { "name": "text", "label": "Input", "query": "12344343333" },
   {
    "name": "testDevice",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Country variable",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select country, max(mm.value)\nfrom devices dd\ninner join (select name, last(value, time) as value from metrics where $__timeFilter(time) group by name) mm\non mm.name=dd.name\ngroup by country;"
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "select state, max(mm.value)\nfrom devices dd\ninner join (select name, last(value, time) as value from metrics where $__timeFilter(time) group by name) mm\non mm.name=dd.name\nwhere country in ($country)\ngroup by state;"
    }
   ]
  },
  {
   "title": "City variable",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select city, max(mm.value)\nfrom devices dd\ninner join (select name, last(value, time) as value from metrics where $__timeFilter(time) group by name) mm\non mm.name=dd.name\nwhere country in ($country) and state in ($state)\ngroup by city;"
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "select name as device, last(value, time) from metrics\nwhere name in (select distinct name from devices where country in ($country) and state in ($state) and city in ($city) and $__timeFilter(time) )\ngroup by name;"
    },
    {
     "rawSql": "select name as device, country, state, city from devices ;"
    }
   ]
  },
  {
   "title": "Minimize",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metrics",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 42, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select name as device, last(value, time) from metrics\nwhere name in (select distinct name from devices where country in ($country) and state in ($state) and city in ($city) and $__timeFilter(time) )\ngroup by name;"
    },
    {
     "rawSql": "select name as device, country, state, city from devices ;"
    },
    {
     "rawSql": "select name as device, country from devices ;"
    }
   ]
  },
  {
   "title": "Minimize view of Metrics with custom icon",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "select name as device, last(value, time) from metrics\nwhere name in (select distinct name from devices where country in ($country) and state in ($state) and city in ($city) and $__timeFilter(time) )\ngroup by name;"
    },
    {
     "rawSql": "select name as device, country, state, city from devices ;"
    },
    {
     "rawSql": "select name as device, country from devices ;"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  value as temp,\n  name\nFROM metrics\nWHERE\n  name in ($device)\n  and $__timeFilter(time)\nORDER BY 1",
     "requestType": "none"
    }
   ]
  },
  {
   "title": "Test Devices",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  value as temp,\n  name\nFROM metrics\nWHERE\n  name in ($device)\n  and $__timeFilter(time)\nORDER BY 1",
     "requestType": "none"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  value as temp,\n  name\nFROM metrics\nWHERE\n  name in ($device)\n  and $__timeFilter(time)\nORDER BY 1",
     "requestType": "none"
    }
   ]
  }
 ]
}